import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.css';

const hubot = localFont({
	src: './fonts/Hubot-Sans.woff2',
	variable: '--font-hubot',
	display: 'swap',
	// weight: '',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${hubot.className} bg-background text-foreground h-[calc(100dvh)] w-full antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
